apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adaptsg-dev
  namespace: argocd
spec:
  project: adaptsg
  source:
    repoURL: https://github.com/BarneyLaw/simplify-next.git
    targetRevision: main
    path: infra/kubernetes/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: adaptsg-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
