apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adaptsg-dev
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`sim-next.lab.packetcraft.dev`)
      services:
        - name: adaptsg-dev
          port: 80
  tls: {}
