apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: adaptsg-dev-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: adaptsg
      app.kubernetes.io/instance: adaptsg-dev
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 8501
          protocol: TCP
