apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adaptsg-dev-workspace
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
